In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Zomato Chennai Listing 2020.csv")
dataset

,Zomato URL,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Dining Rating,Dining Rating Count,Delivery Rating,Delivery Rating Count,Features
0,https://www.zomato.com/chennai/yaa-mohaideen-b...,Yaa Mohaideen Briyani,"336 & 338, Main Road, Pallavaram, Chennai",Pallavaram,['Biryani'],"['Bread Halwa', ' Chicken 65', ' Mutton Biryan...",500.0,4.3,1500,4.3,9306,"['Home Delivery', 'Indoor Seating']"
1,https://www.zomato.com/chennai/sukkubhai-biriy...,Sukkubhai Biriyani,"New 14, Old 11/3Q, Railway Station Road, MKN ...",Alandur,"['Biryani', ' North Indian', ' Mughlai', ' Des...","['Beef Biryani', ' Beef Fry', ' Paratha', ' Pa...",1000.0,4.4,3059,4.1,39200,"['Home Delivery', 'Free Parking', 'Table booki..."
2,https://www.zomato.com/chennai/ss-hyderabad-bi...,SS Hyderabad Biryani,"98/339, Arcot Road, Opposite Gokulam Chit Fun...",Kodambakkam,"['Biryani', ' North Indian', ' Chinese', ' Ara...","['Brinjal Curry', ' Tandoori Chicken', ' Chick...",500.0,4.3,1361,4.4,10500,"['Home Delivery', 'Indoor Seating']"
3,https://www.zomato.com/chennai/kfc-perambur,KFC,"10, Periyar Nagar, 70 Feet Road, Near Sheeba ...",Perambur,"['Burger', ' Fast Food', ' Finger Food', ' Bev...",['Zinger Burger'],500.0,4.0,1101,4.0,11200,"['Home Delivery', 'Free Parking', 'Card Upon D..."
4,https://www.zomato.com/chennai/tasty-kitchen-p...,Tasty Kitchen,"135B, SRP Colony, Peravallur, Near Perambur, ...",Perambur,"['Chinese', ' Biryani', ' North Indian', ' Che...","['Mutton Biryani', ' Chicken Rice', ' Tomato R...",450.0,4.2,617,4.1,22400,"['Home Delivery', 'Indoor Seating']"
...,...,...,...,...,...,...,...,...,...,...,...,...
12027,https://www.zomato.com/chennai/cks-sandwiches-...,CK's Sandwiches,Delivery Only,Porur,['Sandwich'],Invalid,350.0,NaN,NaN,NaN,NaN,"['Breakfast', 'Delivery Only']"
12028,https://www.zomato.com/chennai/cks-sandwiches-...,CK's Sandwiches,Delivery Only,Kolathur,['Sandwich'],Invalid,350.0,NaN,NaN,NaN,NaN,"['Breakfast', 'Delivery Only']"
12029,https://www.zomato.com/chennai/cks-sandwiches-...,CK's Sandwiches,Delivery Only,Anna Nagar East,['Sandwich'],Invalid,350.0,NaN,NaN,NaN,NaN,"['Breakfast', 'Delivery Only']"
12030,https://www.zomato.com/chennai/cks-sandwiches-...,CK's Sandwiches,Delivery Only,Ramapuram,['Sandwich'],Invalid,350.0,NaN,NaN,NaN,NaN,"['Breakfast', 'Delivery Only']"
12031,https://www.zomato.com/chennai/cks-sandwiches-...,CK's Sandwiches,Delivery Only,Sholinganallur,['Sandwich'],Invalid,350.0,NaN,NaN,NaN,NaN,"['Breakfast', 'Delivery Only']"

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Zomato URL             12032 non-null  object
 1   Name of Restaurant     12032 non-null  object
 2   Address                12032 non-null  object
 3   Location               12032 non-null  object
 4   Cuisine                12032 non-null  object
 5   Top Dishes             12032 non-null  object
 6   Price for 2            12032 non-null  float64
 7   Dining Rating          6681 non-null   float64
 8   Dining Rating Count    11812 non-null  object
 9   Delivery Rating        6181 non-null   float64
 10  Delivery Rating Count  11812 non-null  object
 11  Features               12032 non-null  object
dtypes: float64(3), object(9)
memory usage: 1.1+ MB

In [4]:
dataset.columns

Index(['Zomato URL', 'Name of Restaurant', 'Address', 'Location', 'Cuisine',
       'Top Dishes', 'Price for 2', 'Dining Rating', 'Dining Rating Count',
       'Delivery Rating', 'Delivery Rating Count', 'Features'],
      dtype='object')

In [5]:
#access a colunm and find dtype

dataset['Price for 2'].dtype

dtype('float64')

In [6]:
for columnName in dataset.columns:
    if dataset[columnName].dtype == 'O':
        print(columnName)
    else:
        print(columnName)

Zomato URL
Name of Restaurant
Address
Location
Cuisine
Top Dishes
Price for 2
Dining Rating
Dining Rating Count
Delivery Rating
Delivery Rating Count
Features

In [7]:
def quanqual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        if dataset[columnName].dtype == 'O': 
            qual.append(columnName)
        else:
            quan.append(columnName)
    return quan,qual

In [8]:
quanqual(dataset)

(['Price for 2', 'Dining Rating', 'Delivery Rating'],
 ['Zomato URL',
  'Name of Restaurant',
  'Address',
  'Location',
  'Cuisine',
  'Top Dishes',
  'Dining Rating Count',
  'Delivery Rating Count',
  'Features'])

In [9]:
quan,qual = quanqual(dataset)

In [10]:
quan

['Price for 2', 'Dining Rating', 'Delivery Rating']

In [11]:
qual

['Zomato URL',
 'Name of Restaurant',
 'Address',
 'Location',
 'Cuisine',
 'Top Dishes',
 'Dining Rating Count',
 'Delivery Rating Count',
 'Features']

## Central Tendency (MEAN,MEDIAN,MODE)

In [12]:
dataset.describe()

        Price for 2  Dining Rating  Delivery Rating
count  12032.000000    6681.000000      6181.000000
mean     397.611370       3.387756         3.805290
std      332.045938       0.558181         0.374213
min       40.000000       0.300000         0.300000
25%      200.000000       3.100000         3.600000
50%      300.000000       3.500000         3.900000
75%      450.000000       3.800000         4.000000
max     5000.000000       4.900000         4.700000

In [13]:
descriptive = pd.DataFrame()

In [14]:
descriptive

Empty DataFrame
Columns: []
Index: []

In [15]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=quan)

In [16]:
descriptive

       Price for 2 Dining Rating Delivery Rating
Mean           NaN           NaN             NaN
Median         NaN           NaN             NaN
Mode           NaN           NaN             NaN

In [17]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=quan)

for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

In [18]:
descriptive

       Price for 2 Dining Rating Delivery Rating
Mean     397.61137      3.387756         3.80529
Median       300.0           3.5             3.9
Mode         300.0           3.6             3.9

## Percentile (Q1-Min,Q2-Median,Q3-75%,Q4-Max)

In [19]:
import numpy as np

In [20]:
descriptive=pd.DataFrame(index=["Q1:25%","Q2:50%","Q3:75%","99%","Q4:Max"], columns=quan)

In [21]:
descriptive

       Price for 2 Dining Rating Delivery Rating
Q1:25%         NaN           NaN             NaN
Q2:50%         NaN           NaN             NaN
Q3:75%         NaN           NaN             NaN
99%            NaN           NaN             NaN
Q4:Max         NaN           NaN             NaN

In [22]:
descriptive=pd.DataFrame(index=["Q1:25%","Q2:50%","Q3:75%","99%","Q4:Max"], columns=quan)

for columnName in quan:
    #Percentile
    descriptive.loc["Q1:25%", columnName] = dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName] = dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName] = dataset[columnName].quantile(0.75)
    descriptive.loc["99%", columnName] = dataset[columnName].quantile(0.99)
    descriptive.loc["Q4:Max", columnName] = dataset[columnName].quantile(1.0)

In [23]:
descriptive

       Price for 2 Dining Rating Delivery Rating
Q1:25%       200.0           3.1             3.6
Q2:50%       300.0           3.5             3.9
Q3:75%       450.0           3.8             4.0
99%         1969.0           4.5             4.5
Q4:Max      5000.0           4.9             4.7

## IQR

In [24]:
import numpy as np

In [25]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode",
                                "Q1:25%","Q2:50%","Q3:75%","99%","Q4:Max",
                                "IQR","1.5Rule","Lesser-Outliers","Greater-Outliers","Min","Max"], columns=quan)

In [26]:
descriptive

                 Price for 2 Dining Rating Delivery Rating
Mean                     NaN           NaN             NaN
Median                   NaN           NaN             NaN
Mode                     NaN           NaN             NaN
Q1:25%                   NaN           NaN             NaN
Q2:50%                   NaN           NaN             NaN
Q3:75%                   NaN           NaN             NaN
99%                      NaN           NaN             NaN
Q4:Max                   NaN           NaN             NaN
IQR                      NaN           NaN             NaN
1.5Rule                  NaN           NaN             NaN
Lesser-Outliers          NaN           NaN             NaN
Greater-Outliers         NaN           NaN             NaN
Min                      NaN           NaN             NaN
Max                      NaN           NaN             NaN

In [27]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode",
                                "Q1:25%","Q2:50%","Q3:75%","99%","Q4:Max",
                                "IQR","1.5Rule","Lesser_Outliers","Greater_Outliers","Min","Max"], columns=quan)
for columnName in quan:
    #Mean,Median,Mode
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

    #Percentile
    descriptive.loc["Q1:25%", columnName] = dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName] = dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName] = dataset[columnName].quantile(0.75)
    descriptive.loc["99%", columnName] = dataset[columnName].quantile(0.99)
    descriptive.loc["Q4:Max", columnName] = dataset[columnName].quantile(1.0)

    #IQR
    descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName] - descriptive.loc["Q1:25%", columnName]
    descriptive.loc["1.5Rule", columnName] = 1.5 * descriptive.loc["IQR", columnName] 
    descriptive.loc["Lesser_Outliers", columnName] = descriptive.loc["Q1:25%", columnName] - descriptive.loc["1.5Rule", columnName]
    descriptive.loc["Greater_Outliers", columnName] = descriptive.loc["Q3:75%", columnName] + descriptive.loc["1.5Rule", columnName]

    #Min,Max
    descriptive.loc["Min", columnName] = dataset[columnName].min()
    descriptive.loc["Max", columnName] = dataset[columnName].max()

In [28]:
descriptive

                 Price for 2 Dining Rating Delivery Rating
Mean               397.61137      3.387756         3.80529
Median                 300.0           3.5             3.9
Mode                   300.0           3.6             3.9
Q1:25%                 200.0           3.1             3.6
Q2:50%                 300.0           3.5             3.9
Q3:75%                 450.0           3.8             4.0
99%                   1969.0           4.5             4.5
Q4:Max                5000.0           4.9             4.7
IQR                    250.0           0.7             0.4
1.5Rule                375.0          1.05             0.6
Lesser_Outliers       -175.0          2.05             3.0
Greater_Outliers       825.0          4.85             4.6
Min                     40.0           0.3             0.3
Max                   5000.0           4.9             4.7

## Finding and Replacing Outliers

In [29]:
Lesser_Outliers = []
Greater_Outliers = []

for columnName in quan:
    if (descriptive[columnName]['Min'] < descriptive[columnName]['Lesser_Outliers']):
        Lesser_Outliers.append(columnName)
    if (descriptive[columnName]['Max'] > descriptive[columnName]['Greater_Outliers']):
        Greater_Outliers.append(columnName)

In [30]:
Lesser_Outliers

['Dining Rating', 'Delivery Rating']

In [31]:
Greater_Outliers

['Price for 2', 'Dining Rating', 'Delivery Rating']

In [32]:
for columnName in Lesser_Outliers:

    dataset.loc[dataset[columnName] < descriptive.loc["Lesser_Outliers", columnName], columnName] = descriptive.loc["Lesser_Outliers", columnName]

for columnName in Greater_Outliers:

    dataset.loc[dataset[columnName] > descriptive.loc["Greater_Outliers", columnName], columnName] = descriptive.loc["Greater_Outliers", columnName]

In [33]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode",
                                "Q1:25%","Q2:50%","Q3:75%","99%","Q4:Max",
                                "IQR","1.5Rule","Lesser_Outliers","Greater_Outliers","Min","Max"], columns=quan)
for columnName in quan:
    #Mean,Median,Mode
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

    #Percentile
    descriptive.loc["Q1:25%", columnName] = dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName] = dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName] = dataset[columnName].quantile(0.75)
    descriptive.loc["99%", columnName] = dataset[columnName].quantile(0.99)
    descriptive.loc["Q4:Max", columnName] = dataset[columnName].quantile(1.0)

    #IQR
    descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName] - descriptive.loc["Q1:25%", columnName]
    descriptive.loc["1.5Rule", columnName] = 1.5 * descriptive.loc["IQR", columnName] 
    descriptive.loc["Lesser_Outliers", columnName] = descriptive.loc["Q1:25%", columnName] - descriptive.loc["1.5Rule", columnName]
    descriptive.loc["Greater_Outliers", columnName] = descriptive.loc["Q3:75%", columnName] + descriptive.loc["1.5Rule", columnName]

    #Min,Max
    descriptive.loc["Min", columnName] = dataset[columnName].min()
    descriptive.loc["Max", columnName] = dataset[columnName].max()

In [34]:
descriptive

                 Price for 2 Dining Rating Delivery Rating
Mean               364.17761      3.390944        3.817376
Median                 300.0           3.5             3.9
Mode                   300.0           3.6             3.9
Q1:25%                 200.0           3.1             3.6
Q2:50%                 300.0           3.5             3.9
Q3:75%                 450.0           3.8             4.0
99%                    825.0           4.5             4.5
Q4:Max                 825.0          4.85             4.6
IQR                    250.0           0.7             0.4
1.5Rule                375.0          1.05             0.6
Lesser_Outliers       -175.0          2.05             3.0
Greater_Outliers       825.0          4.85             4.6
Min                     40.0          2.05             3.0
Max                    825.0          4.85             4.6

In [35]:
Lesser_Outliers = []
Greater_Outliers = []

for columnName in quan:
    if (descriptive[columnName]['Min'] < descriptive[columnName]['Lesser_Outliers']):
        Lesser_Outliers.append(columnName)
    if (descriptive[columnName]['Max'] > descriptive[columnName]['Greater_Outliers']):
        Greater_Outliers.append(columnName)

In [36]:
Lesser_Outliers

[]

In [37]:
Greater_Outliers

[]

## Frequency | Relative Frequency | Cummulative Relative Frequency

In [38]:
dataset['Price for 2'].value_counts()

Price for 2
300.0    2014
200.0    1970
400.0    1343
250.0    1115
500.0    1064
150.0     923
350.0     920
825.0     635
600.0     506
450.0     439
100.0     340
700.0     238
800.0     195
550.0     176
650.0      87
750.0      50
140.0       4
50.0        3
120.0       2
160.0       1
60.0        1
40.0        1
360.0       1
180.0       1
390.0       1
240.0       1
330.0       1
Name: count, dtype: int64

In [39]:
FreqTable = pd.DataFrame(columns=['Unique_Values','Frequency','Relative_Frequency','cumsum'])
FreqTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, cumsum]
Index: []

In [40]:
def FreqTable(columnName, dataset):

    FreqTable = pd.DataFrame(columns=['Unique_Values','Frequency','Relative_Frequency','cumsum'])
    
    FreqTable["Unique_Values"] = dataset[columnName].value_counts().index
    FreqTable["Frequency"] = dataset[columnName].value_counts().values
    FreqTable["Relative_Frequency"] = FreqTable["Frequency"] / 103
    FreqTable["cumsum"] = FreqTable["Relative_Frequency"].cumsum()
    
    return FreqTable

In [41]:
FreqTable('Price for 2',dataset)

    Unique_Values  Frequency  Relative_Frequency      cumsum
0           300.0       2014           19.553398   19.553398
1           200.0       1970           19.126214   38.679612
2           400.0       1343           13.038835   51.718447
3           250.0       1115           10.825243   62.543689
4           500.0       1064           10.330097   72.873786
5           150.0        923            8.961165   81.834951
6           350.0        920            8.932039   90.766990
7           825.0        635            6.165049   96.932039
8           600.0        506            4.912621  101.844660
9           450.0        439            4.262136  106.106796
10          100.0        340            3.300971  109.407767
11          700.0        238            2.310680  111.718447
12          800.0        195            1.893204  113.611650
13          550.0        176            1.708738  115.320388
14          650.0         87            0.844660  116.165049
15          750.0         50            0.485437  116.650485
16          140.0          4            0.038835  116.689320
17           50.0          3            0.029126  116.718447
18          120.0          2            0.019417  116.737864
19          160.0          1            0.009709  116.747573
20           60.0          1            0.009709  116.757282
21           40.0          1            0.009709  116.766990
22          360.0          1            0.009709  116.776699
23          180.0          1            0.009709  116.786408
24          390.0          1            0.009709  116.796117
25          240.0          1            0.009709  116.805825
26          330.0          1            0.009709  116.815534

## Histogram | Skewness | Kurtosis

In [42]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode",
                                "Q1:25%","Q2:50%","Q3:75%","99%","Q4:Max",
                                "IQR","1.5Rule","Lesser_Outliers","Greater_Outliers","Min","Max","Kurtosis","Skewness"], columns=quan)
for columnName in quan:
    #Mean,Median,Mode
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

    #Percentile
    descriptive.loc["Q1:25%", columnName] = dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName] = dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName] = dataset[columnName].quantile(0.75)
    descriptive.loc["99%", columnName] = dataset[columnName].quantile(0.99)
    descriptive.loc["Q4:Max", columnName] = dataset[columnName].quantile(1.0)

    #IQR
    descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName] - descriptive.loc["Q1:25%", columnName]
    descriptive.loc["1.5Rule", columnName] = 1.5 * descriptive.loc["IQR", columnName] 
    descriptive.loc["Lesser_Outliers", columnName] = descriptive.loc["Q1:25%", columnName] - descriptive.loc["1.5Rule", columnName]
    descriptive.loc["Greater_Outliers", columnName] = descriptive.loc["Q3:75%", columnName] + descriptive.loc["1.5Rule", columnName]

    #Min,Max
    descriptive.loc["Min", columnName] = dataset[columnName].min()
    descriptive.loc["Max", columnName] = dataset[columnName].max()

    #Kurtosis and Skewness
    descriptive.loc["Kurtosis", columnName] = dataset[columnName].kurtosis()
    descriptive.loc["Skewness", columnName] = dataset[columnName].skew()

In [43]:
descriptive

                 Price for 2 Dining Rating Delivery Rating
Mean               364.17761      3.390944        3.817376
Median                 300.0           3.5             3.9
Mode                   300.0           3.6             3.9
Q1:25%                 200.0           3.1             3.6
Q2:50%                 300.0           3.5             3.9
Q3:75%                 450.0           3.8             4.0
99%                    825.0           4.5             4.5
Q4:Max                 825.0          4.85             4.6
IQR                    250.0           0.7             0.4
1.5Rule                375.0          1.05             0.6
Lesser_Outliers       -175.0          2.05             3.0
Greater_Outliers       825.0          4.85             4.6
Min                     40.0          2.05             3.0
Max                    825.0          4.85             4.6
Kurtosis            0.342322      0.281977        0.206868
Skewness            0.991749      -0.59077          -0.488